Compare runtime.

In [1]:
import pandas as pd

filename = '../all_results.csv'

# Load the data
df = pd.read_csv(filename)

# Step 1: Overall avg runtime per algo (used for sorting)
algo_mean = df.groupby('algo')['runtime'].mean().sort_values()

# Step 2: Avg runtime per algo and J
grouped = df.groupby(['algo', 'J'])['runtime'].mean().reset_index()

# Step 3: Pivot the table: rows = algo, cols = J
pivot_table = grouped.pivot(index='algo', columns='J', values='runtime')

# Step 4: Sort rows by overall mean runtime
pivot_table = pivot_table.loc[algo_mean.index]

# Step 5: Round to 2 decimal places and export as LaTeX
pivot_table = pivot_table.round(2)

# Save to LaTeX file
pivot_table.to_latex('algo_runtime_table.tex', float_format="%.2f")

pivot_table

J                   50       200      500       1000
algo
UCL GMM             2.83     3.29     4.21      6.33
DEBM                3.71     4.18     4.40      5.51
UCL KDE             2.66     3.15     4.45      8.84
DEBM GMM            7.53     8.36     9.27     12.23
Hard K-Means        1.26     3.97    10.45     27.46
MLE                 2.77    10.47    31.10     82.04
EM                  2.56     9.91    31.33     98.28
Conjugate Priors   16.10    23.81    44.55     95.34
KDE               225.51  1125.03  4687.41  17490.38