## Get the first table in the publication

In [14]:
import pandas as pd 
df = pd.read_csv('../sample_data/j500_r0.25_Esn_kjOrdinalDM_xnjNormal_m0.csv')
df.drop(['k_j', 'event_time', 'affected'], axis =1, inplace=True)
df.head()

   participant biomarker  measurement  diseased
0            0   FUS-FCI    27.158535      True
1            0     P-Tau    -6.137449      True
2            0      MMSE    24.490713      True
3            0        AB   147.988639      True
4            0   HIP-FCI     1.593390      True

In [15]:
diseased_dict = dict(zip(df.participant, df.diseased))
dff = df.pivot(index='participant', columns='biomarker', values='measurement')
# sort biomarkers by alphabet in ascending order
dff = dff.sort_index(axis=1, level=1, sort_remaining=False)
# remove column name (biomarker) to clean display
dff.columns.name = None
# bring 'participant' back as a column  
dff.reset_index(inplace=True)  
dff['Impacted'] = ['Yes' if diseased_dict[x] else 'No' for x in dff['participant']]

# Reorder columns: keep participant first, then Impacted, then all others
cols = dff.columns.tolist()
cols.insert(1, cols.pop(cols.index('Impacted')))  # Move 'Impacted' to index 1
dff = dff[cols]
dff.drop(columns=['participant'], inplace=True)
dff.head()

,Impacted,AB,ADAS,AVLT-Sum,FUS-FCI,FUS-GMI,HIP-FCI,HIP-GMI,MMSE,P-Tau,PCC-FCI
0,Yes,147.988639,6.634805,39.972976,27.158535,0.649553,1.593390,0.471415,24.490713,-6.137449,2.802075
1,Yes,157.128778,5.693228,31.710924,17.200334,0.610817,-4.057692,0.276723,24.434377,57.889114,8.838792
2,Yes,158.121500,5.600925,26.491547,13.994610,0.650343,6.479192,0.559267,20.872773,62.506348,4.419212
3,No,275.641432,5.629902,56.296766,3.381846,0.637420,-2.935283,0.529496,27.045216,26.226761,10.675277
4,Yes,275.553925,7.375141,41.594103,13.586439,0.492504,-6.421159,0.488737,28.303396,-48.249117,14.504022

In [16]:
# First 3 diseased participants
diseased_df = dff[dff['Impacted'] == 'Yes'].head(3)

# First 3 healthy participants
healthy_df = dff[dff['Impacted'] == 'No'].head(3)

# Combine them if you want a single table
combined_df = pd.concat([diseased_df, healthy_df], ignore_index=True)
combined_df = combined_df[['Impacted', 'FUS-FCI', 'P-Tau', 'MMSE', 'AB', 'HIP-FCI', 'PCC-FCI']]
combined_df

  Impacted    FUS-FCI      P-Tau       MMSE          AB   HIP-FCI    PCC-FCI
0      Yes  27.158535  -6.137449  24.490713  147.988639  1.593390   2.802075
1      Yes  17.200334  57.889114  24.434377  157.128778 -4.057692   8.838792
2      Yes  13.994610  62.506348  20.872773  158.121500  6.479192   4.419212
3       No   3.381846  26.226761  27.045216  275.641432 -2.935283  10.675277
4       No   9.903830  20.596736  28.966988  242.107231 -2.811654   5.691772
5       No   9.286050  40.001014  26.532140  343.847078 -3.557949   7.308004

In [17]:
combined_df.to_csv('table1.csv', index=False)